[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]


# dependencies might appear in plugins as well
async-trait = "0.1"
futures = "0.3"
tokio = { version = "1.6", features = ["full"] }
serde = "1.0"
mime_guess = "2.0"
